### PR TITLE
Added: toast.error() function

### PR DESCRIPTION
**Pull request by MeenuyD**
Similar to toast.success() Added the option to toast an error.
#6

### CODE REVIEW

**Comment by gxrsti** [comment]
Hey @MeenuyD, thanks for contributing!
For this to be merged the logic for .error() needs to be implemented in the package src. toast.error() does not exist yet.

Could you implement this?

**Comment by MeenuyD** [comment]
in which file.

**Comment by gxrsti** [comment]
core/toast.ts

Also an error icon would be cool.
Can be implemented similar to the success icon in components/toast.tsx

**Review by gxrsti — CHANGES_REQUESTED** [review]
There is a build error, please look into it: 
`src/core/toast.ts(8,22): error TS2345: Argument of type '"error"' is not assignable to parameter of type 'ToastType'.`

I also requested some minor changes, would be awesome if you can implement them.
Thank you!

**Review by gxrsti — APPROVED** [review]
Looks good to me now, thank you again for contributing!

**Pull request merged**
