### PR TITLE
Allow users to change toast stacking order

### LINKED ISSUE #12: Allow Changing Direction Of Toasts
A new property called `reverse` should be added to the <Toaster/> component. It should toggle the direction of the toasts. Normally toasts should add to the bottom. If reverse is true, toasts should be added to the top.

Additionally, please add a toggle to the demo website which allows users to toggle the direction!

### PR DESCRIPTION
**Pull request by mjubair**
This PR allows users to change toast message direction based on props

Fixes #12

### CODE REVIEW

**Comment by gxrsti** [comment]
Hey @mjubair, thanks for contributing!

2 minor things that I would like to get implemented before merging this PR:

- Change the select button to a switch with a label (https://ui.shadcn.com/docs/components/switch)
- Forward the index of `reversedToasts.map(toast, index)` to the toast component and assign it to the zIndex so that the toasts always stay behind each other

**Comment by mjubair** [comment]
@gxrsti I have fixed the suggestions you have mentioned above. Please review and let me know if it meets your requirements. Thanks.

**Review by gxrsti — APPROVED** [review]
Looks good to me, thank you again for contributing!

**Comment by mjubair** [comment]
Thank you so much for approving my contribution! I look forward to more contributions in the future.

**Pull request merged**
