### PR TITLE
Workflow to automate Build & Test

### PR DESCRIPTION
**Pull request by Hackerbone**
This a resolution to issue #2 

Any Pull Request opened on the `master` branch will have the action triggered which checks build and tests

### CODE REVIEW

**Comment by Hackerbone** [comment]
Hi @gxrsti, you can review this PR and let me know if it's good to go!

**Comment by gxrsti** [comment]
Hey @Hackerbone,
Thanks for contributing!
Looks good, just these minor adjustments would be awesome:
Could you rename the workflow to ‚Continuous Integration‘ and is it possible to split it up in 2 jobs called ‚test‘ and ‚build'?

**Comment by Hackerbone** [comment]
Sure, I'll get this done 👍

**Comment by Hackerbone** [comment]
Done @gxrsti, this should work

**Comment by gxrsti** [comment]
Perfect, thank you!

**Review by gxrsti — APPROVED** [review]

**Pull request merged**
